# Generated by Django 4.0.4 on 2023-01-16 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10, verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10, verbose_name='Model')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predcar.mark', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modele',
            },
        ),
        migrations.CreateModel(
            name='Pred_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')], verbose_name='Rok produkcji')),
                ('mileage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000000), django.core.validators.MinValueValidator(1)], verbose_name='Przebieg km:   max przebieg do 2000000km')),
                ('vol_engine', models.PositiveIntegerField(max_length=6, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(0)], verbose_name='Pojemniść silnika : między 500cm3 a 5000cm3')),
                ('fuel', models.PositiveIntegerField(choices=[(0, 'Diesel'), (1, 'Elektryczny'), (2, 'Benzyna'), (3, 'Hybryda'), (4, 'LPG')], max_length=10, verbose_name='Rodzaj paliwa')),
                ('province', models.PositiveIntegerField(choices=[(0, 'Dolnośląskie'), (1, 'Kujawsko-pomorskie'), (2, 'Lubelskie'), (3, 'Lubuskie'), (4, 'Mazowieckie'), (5, 'Małopolskie'), (6, 'Opolskie'), (7, 'Podkarpackie'), (8, 'Podlaskie'), (9, 'Pomorskie'), (10, 'Warmińsko-mazurskie'), (11, 'Wielkopolskie'), (12, 'Zachodniopomorskie'), (13, 'Łódzkie'), (14, 'Śląskie'), (15, 'Świętokrzyskie')], max_length=10, verbose_name='Województwo')),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predcar.mark', verbose_name='Marka')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='predcar.model', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Predykcja',
                'verbose_name_plural': 'Predykcje',
            },
        ),
    ]
