# Generated by Django 4.0.4 on 2023-01-16 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pred_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(10)], verbose_name='Mertaż')),
                ('room_num', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='Liczba pokoi')),
                ('floor', models.PositiveIntegerField(choices=[(1, 'Pierwsze'), (2, 'Drugie'), (3, 'Trzecie'), (4, 'Czwarte'), (5, 'Piąte'), (6, 'Szóste'), (7, 'Siudme'), (8, 'Ósme'), (9, 'Dziewiąte'), (10, 'Dziesiąte'), (11, 'Jedenaste')], verbose_name='Piętro')),
                ('total_floor', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='Ilość pięter')),
                ('year_built', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)], verbose_name='Rok budynku')),
                ('dish_washer', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Zmywarka')),
                ('tv_set', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Telewizor')),
                ('washer', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Pralka')),
                ('balcony', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Balkon')),
                ('basement', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Piwnica')),
                ('elevator', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Winda')),
                ('internet', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Internet')),
                ('available_for_students', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Dla studentów')),
                ('two_level', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Dwupoziomowe')),
                ('garden', models.PositiveIntegerField(choices=[(0, 'Nie'), (1, 'Tak')], verbose_name='Ogród')),
                ('district', models.PositiveIntegerField(choices=[(1, 'Bemowo'), (2, 'Białołęka'), (3, 'Bielany'), (4, 'Centrum'), (5, 'Mokotów'), (6, 'Ochota'), (7, 'Praga-Południe'), (8, 'Praga-Północ'), (9, 'Targówek'), (10, 'Ursus'), (11, 'Ursynów'), (12, 'Wawer'), (13, 'Wilanów'), (14, 'Wola'), (15, 'Włochy'), (16, 'Śródmieście'), (17, 'Żoliborz')], verbose_name='Dzielnica')),
            ],
            options={
                'verbose_name': 'Predykcja wynajmu mieszkania w warszawie',
                'verbose_name_plural': 'Predykcja wynajmu mieszkania w warszawie',
            },
        ),
    ]
